name: "Esporta iOS"
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0
          use-mono: false

      - name: Esporta Progetto Xcode
        run: |
          mkdir -p build/ios
          godot --headless --export-release "iOS" build/ios/The-Jumping-Fox.xcodeproj
          
      - name: Carica Risultato
        uses: actions/upload-artifact@v4
        with:
          name: Progetto-Xcode-iOS
          path: build/ios
