name: build
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0
      - run: |
          mkdir -p build/ios
          godot --headless --path . --export-release "iOS" build/ios/game.xcodeproj
      - uses: actions/upload-artifact@v4
        with:
          name: ios-export
          path: build/ios
