name: "Esporta iOS"
on: [push] # Si avvia ogni volta che carichi modifiche

jobs:
  export-ios:
    runs-on: macos-latest # Qui GitHub user√† un vero Mac virtuale
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0 # Metti la tua versione di Godot (es. 4.2.2)

      - name: Esporta Progetto Xcode
        run: |
          mkdir -p build/ios
          godot --headless --export-release "iOS" build/ios/il_tuo_gioco.xcodeproj
          
      - name: Carica Risultato
        uses: actions/upload-artifact@v4
        with:
          name: Progetto-Xcode-iOS
          path: build/ios
